updated build/install scripts based on Nikola Lecic's patches
git-svn-id: http://scripts.sil.org/svn-public/xetex/TRUNK@503 9f0520aa-a7ea-0310-80d7-d2976a5bef54

diff --git a/build-xetex b/build-xetex
--- a/build-xetex
+++ b/build-xetex
@@ -3,8 +3,38 @@
 # Top-level script to compile xetex (and xdv2pdf on OS X)
 # from the source tree as found in Subversion
 
+echo "###### CONFIGURING XETEX"
+
+real_path() # function to resolve symlinks in path, as not everyone has realpath(1)
+{
+	current_path=`pwd` && relative_path="$1"
+	cd -P "${relative_path}"
+	real_path=`pwd` && cd "${current_path}"
+	echo "${real_path}"
+}
+
+test -z "${GNUMAKE}" && {
+	GNUMAKE=`which gnumake`
+	if [ ! -e "${GNUMAKE}" ]; then
+		GNUMAKE=`which gmake`
+	fi
+	if [ ! -e "${GNUMAKE}" ]; then
+		GNUMAKE=`which make`
+	fi
+	if [ ! -e "${GNUMAKE}" ]; then
+		echo "### There is no 'make' in your system."
+		exit 1
+	fi
+}
+
+is_gnu_make=`${GNUMAKE} -v | grep -c -i "GNU Make"`
+if [ "${is_gnu_make}" = "0" ]; then
+	echo "### You need GNU Make (gmake, gnumake) to build XeTeX."
+	exit 1
+fi
+
 # do some cleanup if needed
-test ! -f Makefile || make clean
+test ! -f Makefile || ${GNUMAKE} clean
 rm -rf Work
 find . -name config.cache -print -exec rm -f {} \;
 
@@ -14,27 +44,74 @@ find . -name configure -exec chmod +x {} \;
 test -d libs/icu-xetex -o -L libs/icu-xetex || ln -fs icu-release-3-6-source libs/icu-xetex
 
 # run the configure script, which will create a Work subtree
-bash ./runConfigure.sh
+sh ./runConfigure.sh
+
+echo "###### BUILDING LIBRARIES AND XETEX"
 
 # make libraries first (not handled by the xetex makefile)
+LIBS=`find Work/libs -type d -maxdepth 1 -mindepth 1 | sed -e 's/Work\/libs\///'`
 if [ "`uname`" = "Darwin" ]; then
-	LIBS="teckit icu-xetex graphite-engine freetype2"
-else
-	LIBS="teckit icu-xetex graphite-engine freetype2 libpng xpdf"
+	# don't need libpng or xpdf on Darwin; we use QuickTime & Quartz
+	LIBS=`echo "$LIBS" | grep -v 'libpng\|xpdf'`
 fi
+echo "### Static libs to be built:"
+echo "${LIBS}"
 for f in ${LIBS}; do
-	(cd Work/libs/${f} && make)
+	( cd Work/libs/${f} && echo "### Running ${GNUMAKE} in `pwd`" && ${GNUMAKE} )
 done
 
 # make the xetex binary
-(cd Work/texk/web2c && make web2cdir=`dirname \`kpsewhich texmf.cnf\`` xetex)
+
+	# -------
+	# This is the copy of determining the presence of symlinks in
+	# web2c path as reported by kpsewhich (as used in runConfigure.sh);
+	# it would be nice if there is a more elegant way to pass it here.
+
+	# try to figure out where the user's TeX is, and complain if we can't find it...
+	KPSEWHICH=`which kpsewhich`
+	if [ ! -e "${KPSEWHICH}" ]; then
+		echo "### No kpsewhich found -- are you sure you have TeX installed?"
+		exit 1
+	else
+		using_tex_dist=`dirname ${KPSEWHICH} | grep -c texbin`
+		if [ "${using_tex_dist}" = "1" ]; then
+			# Looks like we've got a Mac OS X "TeX Distributions" structure;
+			# we can't use this as a build prefix - must find the real location
+			kpsewhich_dir=`dirname ${KPSEWHICH}`
+			echo "### Resolving TeXDist path ${kpsewhich_dir} to real location"
+			real_bin_dir=`real_path ${kpsewhich_dir}`
+			echo "### Real binaries location: ${real_bin_dir}"
+			PREFIX=`echo ${real_bin_dir} | sed -e 's!/bin/.*!!;'`
+		else
+			PREFIX=`echo ${KPSEWHICH} | sed -e 's!/bin/.*!!;'`
+		fi
+		if [ ! -d "${PREFIX}" ]; then
+			echo "### PREFIX ${PREFIX} is not a directory; cannot continue."
+			exit 1
+		fi
+	fi
+	
+	WEB2CDIR=`dirname \`kpsewhich texmf.cnf\``
+	REALPATHPREFIX=`real_path ${PREFIX}`
+	if [ ! "${REALPATHPREFIX}" = "${PREFIX}" ]; then
+		if [ "`echo ${WEB2CDIR} | sed -e 's!${REALPATHPREFIX}!!'`" = "${WEB2CDIR}" ]; then
+			WEB2CDIR=`echo ${WEB2CDIR} | sed -e 's!${REALPATHPREFIX}!${PREFIX}!'`
+			echo "### WEB2CDIR seems to contain symlink; honouring it."
+		fi
+	fi
+	# -------
+
+echo "### Making xetex binary using: 'cd Work/texk/web2c && ${GNUMAKE} web2cdir=${WEB2CDIR} xetex'"
+(cd Work/texk/web2c && ${GNUMAKE} web2cdir=${WEB2CDIR} xetex)
 PRODUCTS=Work/texk/web2c/xetex
 
-# xdv2pdf is for Mac OS X only, don't try to build on Linux
+# xdv2pdf is for Mac OS X only, don't try to build on Linux or *BSD.
 if [ "`uname`" = "Darwin" ]; then
-	(cd Work/texk/xdv2pdf && make all)
+	(cd Work/texk/xdv2pdf && ${GNUMAKE} all)
 	PRODUCTS="${PRODUCTS} Work/texk/xdv2pdf/xdv2pdf Work/texk/xdv2pdf/T1Wrap"
 fi
 
 # show the executables we made (assuming the build was successful)
+echo "### Products built successfully:"
+find ${PRODUCTS} -type f -exec strip {} \;
 ls -l ${PRODUCTS}
diff --git a/install-xetex b/install-xetex
--- a/install-xetex
+++ b/install-xetex
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # FIXME: this should all be replaced by "make install" eventually,
 # as part of proper integration with the TeX Live build
@@ -6,11 +6,14 @@
 # script to install xetex (and xdv2pdf on OS X)
 # from the binaries created by build-xetex
 
-# this is intended for the Linux version; on OS X, we build installer packages
+# this is intended for the Linux and *BSD version;
+# on OS X, we build installer packages
 
 # to be run from the top level dir of the xetex tree, after ./build-xetex
 
 # set -o xtrace
+
+echo "###### INSTALLING XETEX"
 
 filelist=Work/xetex-installed-files
 
@@ -26,15 +29,20 @@ texbin=`which tex`
 if [ ! -x "${texbin}" ]; then
 	echo "### error: existing tex binary couldn't be found"
 	exit 100
+else
+	echo "### TeX binary = ${texbin}"
 fi
 if [ -L ${texbin} ]; then
 	texbin=`readlink ${texbin}`
+	echo "### TeX binary (${texbin}) seems to be symlinked."
 fi
 texbindir=`dirname ${texbin}`
+echo "### TeX bin directory = ${texbindir}"
 
 # copy the xetex binary to the same dir as standard tex
 cp -pf Work/texk/web2c/xetex ${texbindir}/xetex
 echo ${texbindir}/xetex >> ${filelist}
+
 if [ -e Work/texk/xdv2pdf/xdv2pdf ]; then
 	programs="xdv2pdf T1Wrap"
 	for f in ${programs}; do
@@ -45,11 +53,25 @@ fi
 
 # copy our texmf additions into the local texmf tree
 texmflocal=`kpsewhich --var-value TEXMFLOCAL`
-if [ "x${texmflocal}" == "x" ]; then
+if [ -z "${texmflocal}" ]; then
 	# if --var-value didn't work, try to find the definition in the texmf.cnf file
 	CNF=`kpsewhich texmf.cnf`
-	texmflocal=`sed -rne "s/^[ \t]*TEXMFLOCAL[ \t]*=[ \t]*(\/[^ \t]+).*/\1/p" ${CNF}`
+	texmflocal=`grep '^[ \t]*TEXMFLOCAL[ \t]*=[ \t]*/' ${CNF}`
+	if [ -z "${texmflocal}" ]; then
+		echo "### error: unable to find usable TEXMFLOCAL definition"
+		exit 100
+	fi
+	texmflocal=`echo ${texmflocal} | awk -F "=[ \t]*" '{print $2}'`
 fi
+# Figuring out whether texmflocal contains symlinks (as we did in
+# runConfigure.sh and build-xetex) is not necessary here, since this
+# path is used just for mechanical copying, _except_ for texhash.
+# Does texhash's behaviour differ depending on whether the path it
+# uses respects symlinks?
+# 
+# What fmtutil does depends however on kpsewhich, which is beyond
+# the scope of this installation script.
+echo "### Using TEXMFLOCAL = ${texmflocal}"
 
 mkdir -p ${texmflocal}
 if [ -d texmf/.svn ]; then
@@ -64,14 +86,24 @@ else
 fi
 find texmf -type f -and -not -path "*/.*" -print | sed -e "s@^texmf@${texmflocal}@" >> ${filelist}
 
-# copy the pool file to /web2c under TEXMFLOCAL
-mkdir -p ${texmflocal}/web2c
-cp -pf Work/texk/web2c/xetex.pool ${texmflocal}/web2c/xetex.pool
-echo ${texmflocal}/web2c/xetex.pool >> ${filelist}
-
 # update kpathsearch databases because we've installed a bunch of stuff
+echo "### Running texhash"
 texhash ${texmflocal}
 
 # this will build the format files on the system where this script is run;
 # for packaged binary installations, we must repeat this on the target
+
 sh ./rebuild-formats
+echo "### All done. You installed xetex successfully. Newly installed files are:"
+cat ${filelist}
+echo "### Output of 'xetex --version:'"
+xetex --version
+
+echo "### NOTE: If you have locally installed xe(la)tex.fmt"
+echo "### (~/.texlive2007/texmf-var/web2c/xetex/ is TeXLive's"
+echo "### default directory), then you can expect the following"
+echo "### error when run your new xetex for the first time:"
+echo "###     [...]/xelatex.fmt doesn't match xetex.pool"
+echo "###     (Fatal format file error; I'm stymied)"
+echo "### You should delete the old .fmt files."
+# Is installing new local .fmt's using fmtutil --enablefmt/--byfmt necessary?
diff --git a/rebuild-formats b/rebuild-formats
--- a/rebuild-formats
+++ b/rebuild-formats
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # script to create initial xetex and xelatex formats, after installation
 
@@ -6,12 +6,12 @@
 
 # ensure our entries are present in fmtutil.cnf
 fmtutil_cnf=`kpsewhich --format="web2c files" fmtutil.cnf`
-if [ "`fgrep -c xetex ${fmtutil_cnf}`" == "0" ]; then
+if [ ! "`grep xetex ${fmtutil_cnf}`" ]; then
 	cat >> ${fmtutil_cnf} <<-__EOT__;
 
 	# XeTeX formats
-	xetex	xetex	-	*xetex.ini
-	xelatex	xetex	language.dat	*xelatex.ini
+	xetex	xetex	-	-etex xetex.ini
+	xelatex	xetex	language.dat	-etex xelatex.ini
 	
 	__EOT__
 fi
@@ -32,14 +32,29 @@ PATH=${texbindir}:$PATH
 patch -N -r /tmp/fmtutilpatch.rej -p0 `which fmtutil` < fmtutil.tetex-2.patch >/dev/null 2>&1
 
 # use system-wide setup if available
-fmtutil=`type -p fmtutil-sys` || fmtutil=`type -p fmtutil`
+# This can't run with BSD sh; I hope that the following
+# is what was intended:
+# fmtutil=`type -p fmtutil-sys` || fmtutil=`type -p fmtutil`
+fmtutil=`which fmtutil-sys`
+if [ ! -e "${fmtutil}" ]; then
+	fmtutil=`which fmtutil`
+	if [ ! -e "${fmtutil}" ]; then
+		echo "### Can't find fmtutil! Giving up... check your TeX installation."
+		exit 1
+	fi
+	echo "### Can't find system-wide fmtutil; using ${fmtutil}"
+else
+	echo "### Using system-wide fmtutil: ${fmtutil}"
+fi
 
 formats="xetex xelatex"
 for f in ${formats}; do
 # enable our entries if necessary (in case of pre-existing disabled ones)
+	echo "### Running ${fmtutil} for format ${f}"
 	${fmtutil} --enablefmt ${f}
 	${fmtutil} --byfmt ${f}
 done
 
 # create symlinks for the newly-built formats
+echo "### Creating symlinks for the newly-built formats"
 texlinks --silent
