Sync with TeXLive tree

diff --git a/texk/kpathsea/mktexlsr b/texk/kpathsea/mktexlsr
--- a/texk/kpathsea/mktexlsr
+++ b/texk/kpathsea/mktexlsr
@@ -11,7 +11,7 @@
 # <te@dbs.uni-hannover.de>, Okt., 1994.
 # Public domain.
 
-version='$Id: mktexlsr 14402 2009-07-23 17:09:15Z karl $'
+version='$Id: mktexlsr 23151 2011-06-27 22:27:02Z karl $'
 progname=`echo $0 | sed 's%.*/%%'`
 usage="Usage: $progname [OPTION]... [DIR]...
 
@@ -30,7 +30,7 @@ Options:
   
 If standard input is a terminal, --verbose is on by default.
 
-For more information, see the &lsquo;Filename database&rsquo; section of
+For more information, see the \`Filename database' section of
 Kpathsea manual available at http://tug.org/kpathsea.
 
 Report bugs to tex-k@tug.org.
@@ -66,6 +66,10 @@ if tty -s; then verbose=true; else verbose=false; fi
 dry_run=false
 trees=
 
+treefile="${TMPDIR-/tmp}/mktexlsrtrees$$.tmp"
+trap 'cd /; rm -f $treefile; test -z "$db_dir_tmp" || rm -rf "$db_dir_tmp"; 
+      exit' 0 1 2 3 7 13 15
+
 # A copy of some stuff from mktex.opt, so we can run in the presence of
 # terminally damaged ls-R files.
 while test $# -gt 0; do
@@ -86,11 +90,24 @@ while test $# -gt 0; do
   elif test "x$1" = x--; then
     :
   elif echo "x$1" | grep '^x-' >/dev/null; then
-    echo "$progname: unknown option $1, try --help if you need it." >&2
+    echo "$progname: unknown option \`$1', try --help if you need it." >&2
     exit 1
   else
-    test -d "$1" || echo "$progname: $1 not a directory." >&2
-    trees="$trees $1"  # don't want to update system dirs
+    if test ! -d "$1"; then
+      echo "$progname: $1: not a directory, skipping." >&2
+      shift
+      continue
+    fi
+    # By saving the argument in a file, we can later get it back while
+    # supporting spaces in the name.  This still doesn't support
+    # newlines in the directory names, but nobody ever complains about
+    # that, and it seems much too much trouble to use \0 terminators.
+    (umask 077
+    if echo "$1" >>"$treefile"; then :; else
+      echo "$progname: $treefile: could not append to arg file, goodbye." >&2
+      exit 1
+    fi
+    )
   fi
   shift
 done
@@ -101,20 +118,19 @@ ls_R_magic='% ls-R -- filename database for kpathsea; do not change this line.'
 # The old string, which should continue to work.
 old_ls_R_magic='% ls-R -- maintained by MakeTeXls-R; do not change this line.'
 
-trap 'cd /; test -z "$db_dir_tmp" || rm -rf "$db_dir_tmp"; exit' 0 1 2 3 7 13 15
-
-# Get list of directories from $TEXMFDBS; eliminate duplicates.
 {
-  if test -n "$trees"; then
-    set x $trees
-  else
-    OIFS=$IFS  # want just a newline
-    IFS='
+  # Get list of directories from the explicit arguments (now saved in
+  # $treefile), or $TEXMFDBS if no explicit args.  Eliminate duplicates.
+  saveIFS=$IFS  # break only at newline
+  IFS='
 '
+  if test -s "$treefile"; then
+    set x `sort "$treefile" | uniq`
+  else
     set x `kpsewhich --show-path=ls-R | tr : '
 ' | sort | uniq`
-    IFS=$OIFS
   fi
+  IFS=$saveIFS
   shift
 }
 
@@ -156,16 +172,16 @@ for TEXMFLS_R in "$@"; do
   elif test -s "$db_file" \
        && test "x`sed '1s/$//;1q' \"$db_file\"`" != "x$ls_R_magic" \
        && test "x`sed '1s/$//;1q' \"$db_file\"`" != "x$old_ls_R_magic"; then
-    echo "$progname: $db_file lacks magic string. Skipping..." >&2
+    echo "$progname: $db_file: no magic string, skipping..." >&2
     continue
   fi
 
   # Skip if we cannot write the file:
-  kpseaccess -w "$db_file" || { echo "$progname: $db_file: no write permission. Skipping..." >&2; continue; }
+  kpseaccess -w "$db_file" || { echo "$progname: $db_file: no write permission, skipping..." >&2; continue; }
 
   db_dir_tmp="$db_dir/lsR$$.tmp"
   (umask 077 && mkdir "$db_dir_tmp" ) \
-    || { echo "$progname: could not create directory '$db_dir_tmp'. Skipping..." >&2; continue; }
+    || { echo "$progname: $db_dir_tmp: could not create directory, skipping..." >&2; continue; }
   db_file_tmp="$db_dir_tmp/lsR$$.tmp"
   rm -f "$db_file_tmp"
 
@@ -183,7 +199,7 @@ for TEXMFLS_R in "$@"; do
   # in directory names.
   # 
   echo "./:" >>"$db_file_tmp"
-  vc_dirs='\.\(bzr\|git\|hg\|svn\)\|CVS\|RCS\|_darcs'
+  vc_dirs='\.\(bzr\|git\|hg\|svn\)\|_darcs'
   (cd "$TEXMFLS_R" && \ls -LRa 2>/dev/null) \
    | sed -e '/^$/{n;s%^\./%%;s%^%./%;}; /^\.$/d; /^\.\.$/d; /^'$vc_dirs'$/d;' \
          -e '/^[\.\/]*lsR[0-9]*\.tmp:*$/d' \
