updated kpathsea and web2c source to 7.5.5
git-svn-id: http://scripts.sil.org/svn-public/xetex/TRUNK@271 9f0520aa-a7ea-0310-80d7-d2976a5bef54

diff --git a/texk/kpathsea/mktexpk b/texk/kpathsea/mktexpk
--- a/texk/kpathsea/mktexpk
+++ b/texk/kpathsea/mktexpk
@@ -7,7 +7,7 @@
 # te@dbs.uni-hannover.de, kb@mail.tug.org, and infovore@xs4all.nl.
 # Public domain.
 
-version='$Id: mktexpk,v 1.31 2004/04/01 20:50:01 olaf Exp $'
+version='$Id: mktexpk,v 1.34 2005/06/21 10:49:10 olaf Exp $'
 progname=`echo $0 | sed 's%.*/%%'`
 usage="Usage: $progname [OPTIONS] NAME [REDIRECT],
   Create a PK font.
@@ -116,12 +116,16 @@ if kpsewhich $NAME.mf >/dev/null 2>&1 || mktexmf $NAME >/dev/null 2>&1; then
      100) MODE=nextscrn;;
      180) MODE=toshiba;;
      300) MODE=cx;;
+     360) MODE=epstylus;;
      400) MODE=nexthi;;
      600) MODE=ljfour;;
+     720) MODE=epsczz;;
+    1200) MODE=ultre;;
     1270) MODE=linoone;;
     8000) MODE=dpdfezzz;;
        *) echo "$progname: Can't guess mode for $BDPI dpi devices." >&2
-          echo "$progname: Use a config file, or update me." >&2
+          echo "$progname: Use a config file or option to specify the mode; see:" >&2
+          echo "$progname: http://tug.org/texinfohtml/kpathsea.html#Unable-to-generate-fonts" >&2
           exit 1
     esac
   fi
